# Generated by Django 4.0.3 on 2022-04-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID telegram')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=100, null=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdays.user', verbose_name='ID telegram')),
            ],
            options={
                'verbose_name': 'День рождения',
                'verbose_name_plural': 'Дни рождения',
            },
        ),
    ]
